### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by rickyman20** [dreid93/atom-makro#12]
[Enter steps to reproduce below:]

1. Pressed `ctr+alt+x`

Running Elementary OS Freya

**Atom Version**: 0.176.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [makro](https://github.com/dreid93/atom-makro) package, v0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /home/rdelfin/.atom/packages/makro/lib/views/makefile_view.coffee:60

TypeError: Cannot read property 'path' of undefined
  at MakefileView.module.exports.MakefileView.setMakefile (/home/rdelfin/.atom/packages/makro/lib/views/makefile_view.coffee:60:29)
  at Object.module.exports.toggleMainMakefile (/home/rdelfin/.atom/packages/makro/lib/index.coffee:92:19)
  at atom-workspace.<anonymous> (/home/rdelfin/.atom/packages/makro/lib/index.coffee:13:48)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:00.5 makro:toggleMainMakefile (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
isotope-ui, v1.2.6
linter, v0.10.1
makro, v0.2.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dreid93** [comment]
Sorry, I am currently not supporting this project due to my current work load. Please feel free to fork, fix, and submit a PR. It would be greatly appreciated!

**Comment by carneeki** [comment]
+1 I'll attempt to fix it in a few days as it's affecting me too.

OT: @rickyman20 I noticed you're an FRC guy. We're about to do the very first Sydney FRC regional in Australia here, so there's my reason for the delay :)

**Comment by rickyman20** [comment]
@carneeki Oh! Yeah, I just finished high school about a year ago so unfortunately I'm no longer in my team, but I definitely loved FRC! We also had our first regional in Mexico City last year. Good luck at the regional! I wanted to fix it too, but I'm still getting used to the college workload...

**Comment by dreid93** [comment]
@carneeki I was wondering if you had any luck with this? I plan to put some time into this tomorrow.

**Comment by carneeki** [comment]
Sorry - real life got in my way too. Look forward to seeing your results :)
