### ISSUE TITLE
Failed to activate the makro package

### ISSUE THREAD

**Issue by Wolfereign** [dreid93/atom-makro#13]
[Enter steps to reproduce below:]

1. install plugin

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [makro](https://github.com/dreid93/atom-makro) package, v0.2.0

### Stack Trace

Failed to activate the makro package

```
At Cannot read property 'getEntries' of undefined

TypeError: Cannot read property 'getEntries' of undefined
  at Object.module.exports.activate (C:\Users\Wolfereign\.atom\packages\makro\lib\index.coffee:33:14)
  at Package.module.exports.Package.activateNow (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:240:19)
  at C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\Wolfereign\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -1:00.2 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:59.6 feedback:show (feedback-status)
     -0:56.4 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:24.8 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "followSymlinks": true
  },
  "makro": {
    "userId": "71469ae9-188c-4cad-941d-ec7ebbb01541"
  }
}
```

### Installed Packages

```coffee
# User
language-cmake, v0.1.1
language-powershell, v2.0.0
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
makro, v0.2.0
minimap, v4.6.0
script, v2.18.0

# Dev
No dev packages
```

**Comment by dreid93** [comment]
Hey, I am not currently supporting this package. Feel free to submit a PR :)

**Comment by dreid93** [comment]
@Wolfereign is this no longer a problem? Could you explain?

**Comment by nsrosenqvist** [comment]
I still get the this error when launching Atom on Ubuntu.
